// src/hooks/useTerminal.ts
import { useState, useCallback } from 'react';
import {
  CommandHistoryItem,
  TerminalSettings,
  Suggestion,
  DEFAULT_SETTINGS,
  AICommandTranslation,
} from '@/types/terminal';

// Detect Electron environment
const isElectron =
  typeof window !== 'undefined' &&
  window.electronAPI?.isElectron === true;

// ID generator
const generateId = (): string =>
  Date.now().toString(36) + Math.random().toString(36).slice(2);

export function useTerminal() {
  /* =======================
     STATE
  ======================= */

  const [settings, setSettings] =
    useState<TerminalSettings>(DEFAULT_SETTINGS);

  const [commandHistory, setCommandHistory] =
    useState<CommandHistoryItem[]>([]);

  const [currentInput, setCurrentInput] = useState('');
  const [searchQuery, setSearchQuery] = useState('');

  const [suggestions, setSuggestions] = useState<Suggestion[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);

  const [currentTranslation, setCurrentTranslation] =
    useState<AICommandTranslation | null>(null);

  /* =======================
     CORE: PROCESS INPUT
  ======================= */

  const processInput = useCallback(
    async (input: string) => {
      if (!input.trim() || isProcessing) return;

      setIsProcessing(true);
      setSuggestions([]);

      const startTime = Date.now();

      const historyItem: CommandHistoryItem = {
        id: generateId(),
        timestamp: new Date(),
        input,
        naturalLanguage: input,
        shellCommand: '',
        output: '',
        status: 'pending',
      };

      setCommandHistory((prev) => [...prev, historyItem]);
      setCurrentInput('');

      try {
        let output = '';
        let shellCommand = '';
        let explanation = '';

        if (isElectron && window.electronAPI?.runAgent) {
          // REAL execution via preload
          output = await window.electronAPI.runAgent(input);

          // You can enhance this later by returning structured data
          shellCommand = '[generated by AI]';
          explanation = 'Command generated and executed by AI agent.';
        } else {
          // Browser mock mode
          output =
            '[Mock mode]\n' +
            `Input: ${input}\n` +
            'Electron not detected.';
          shellCommand = 'mock-command';
          explanation = 'Mock execution in browser environment.';
        }

        const executionTime = Date.now() - startTime;

        setCommandHistory((prev) =>
          prev.map((item) =>
            item.id === historyItem.id
              ? {
                  ...item,
                  output,
                  shellCommand,
                  aiExplanation: explanation,
                  executionTime,
                  status: 'success',
                }
              : item
          )
        );
      } catch (err: any) {
        setCommandHistory((prev) =>
          prev.map((item) =>
            item.id === historyItem.id
              ? {
                  ...item,
                  output: err?.message ?? 'Unknown error',
                  status: 'error',
                }
              : item
          )
        );
      } finally {
        setIsProcessing(false);
      }
    },
    [isProcessing]
  );

  /* =======================
     INPUT & SUGGESTIONS
  ======================= */

  const updateInput = useCallback((value: string) => {
    setCurrentInput(value);
  }, []);

  const updateSuggestions = useCallback((value: string) => {
    setCurrentInput(value);

    if (!value.trim()) {
      setSuggestions([]);
      return;
    }

    const mockSuggestions: Suggestion[] = [
      {
        id: '1',
        command: 'Create folder named test',
        description: 'Creates a new directory',
        frequency: 10,
        category: 'ai-suggested',
      },
      {
        id: '2',
        command: 'List files in directory',
        description: 'Lists all files',
        frequency: 8,
        category: 'frequent',
      },
    ];

    setSuggestions(mockSuggestions);
  }, []);

  const navigateHistory = useCallback(
    (_direction: 'up' | 'down') => {
      if (commandHistory.length === 0) return;

      const last = commandHistory[commandHistory.length - 1];
      setCurrentInput(last.input);
    },
    [commandHistory]
  );

  /* =======================
     SETTINGS & HISTORY
  ======================= */

  const updateSettings = useCallback(
    (newSettings: TerminalSettings) => {
      setSettings(newSettings);
    },
    []
  );

  const clearTerminal = useCallback(() => {
    setCommandHistory([]);
    setCurrentTranslation(null);
  }, []);

  const searchHistory = useCallback((query: string) => {
    setSearchQuery(query);
  }, []);

  /* =======================
     RETURN API
  ======================= */

  return {
    // state
    settings,
    commandHistory,
    currentInput,
    suggestions,
    isProcessing,
    currentTranslation,
    searchQuery,

    // actions
    processInput,
    updateInput,
    updateSuggestions,
    navigateHistory,
    updateSettings,
    clearTerminal,
    searchHistory,
  };
}
